services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: watcherdb
      POSTGRES_USER: watcher
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U watcher -d watcherdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
